[package]
name = "arna"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Collection of handmade libraries."

[dependencies]

[profile.release]
debug = true
strip = false
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[features]
default = ["alloc", "virtual", "std"]
std = ["alloc"]
alloc = []
virtual = []
example-link-raylib = []
dll = []

[[example]]
name = "raylib-lib"
crate-type = ["cdylib"]
required-features = ["example-link-raylib", "dll"]

[[example]]
name = "raylib"
path = "examples/raylib.rs"
required-features = ["example-link-raylib"]
